name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Test the local action
      - name: Test local action
        uses: ./
        with:
          dist_dir: "test-dist"
          plugin_slug: "test-plugin"
          build_command: |
            mkdir -p test-dist
            cat > test-dist/plugin.php << 'EOF'
            <?php
            /**
             * Plugin Name: Test Plugin
             * Version: 1.0.0
             * Description: A test plugin
             * Author: Test Author
             * License: GPL v2 or later
             */
            EOF
            echo "test content" > test-dist/test.txt
            zip -r test-plugin-1.0.0.zip test-dist
            printf "test-plugin-1.0.0.zip file generated!\n"
          # The echo "test-plugin.zip file generated!" is needed by Digital-Gravy/action-build-zip-file@v1
