name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Test the local action
      - name: Test local action
        uses: ./
        with:
          dist_dir: "test-dist"
          plugin_slug: "test-plugin"
          build_command: |
            mkdir -p test-dist
            echo "test content" > test-dist/test.txt
            cd test-dist && zip test-plugin.zip test.txt
            echo "test-plugin.zip file generated!"
          # The echo "test-plugin.zip file generated!" is needed by Digital-Gravy/action-build-zip-file@v1
